version: "3.9"
services:

  hw_step1:
    image: ubuntu:latest
    container_name: hw_step1
    hostname: hw_step1
    command: bash -c "cd tmp && touch change_me.txt"
    ports:
      - 5000:5000
    volumes:
      - .:/tmp

  hw_step2:
    image: ubuntu:latest
    container_name: hw_step2
    hostname: hw_step2
    command: bash -c "cd tmp && chmod +x change_me.txt"
    ports:
      - 5001:5001
    volumes:
      - .:/tmp


